### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: 7xJAWmK2a83e4cd9d5e8ea4c5zcIgvkn

origin=64999&destination=64942&weight=1000&courier=jne